# Generated by Django 5.0.6 on 2025-01-20 21:44

import backend.base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('setor', models.ManyToManyField(blank=True, related_name='atividades', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('setor', models.ManyToManyField(blank=True, related_name='cliente', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('atividades', models.ManyToManyField(blank=True, related_name='servicos', to='base.atividade')),
                ('setor', models.ManyToManyField(blank=True, related_name='servico', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.DateTimeField(default=backend.base.models.hora_atual, editable=False)),
                ('ativo', models.BooleanField(default=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('duracao', models.DurationField(blank=True, null=True)),
                ('atividade', models.ForeignKey(default='Canva', on_delete=django.db.models.deletion.CASCADE, to='base.atividade')),
                ('cliente', models.ForeignKey(default='Dome', on_delete=django.db.models.deletion.CASCADE, to='base.cliente')),
                ('colaborador', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(default='Outros', on_delete=django.db.models.deletion.CASCADE, to='base.servico')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='servicos',
            field=models.ManyToManyField(blank=True, related_name='clientes', to='base.servico'),
        ),
    ]
