# Generated by Django 5.0.6 on 2025-01-20 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registroatividade',
            old_name='data_fim',
            new_name='data_final',
        ),
        migrations.RenameField(
            model_name='registroatividade',
            old_name='hora',
            new_name='data_inicial',
        ),
    ]
