# Generated by Django 5.0.6 on 2025-01-20 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_data_fim_registroatividade_data_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroatividade',
            name='setor_do_colaborador',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registroatividade',
            name='atividade',
            field=models.ForeignKey(default='Outros', on_delete=django.db.models.deletion.CASCADE, to='base.atividade'),
        ),
    ]
